apiVersion: v1
kind: ServiceAccount
metadata:
  name: env-injector-controller-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: env-injector-controller-role
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["get", "watch", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: env-injector-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: env-injector-controller-role
subjects:
- kind: ServiceAccount
  name: env-injector-controller-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-injector-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: env-injector-controller
  template:
    metadata:
      labels:
        app: env-injector-controller
    spec:
      containers:
      - name: env-injector-controller
        image: env-injector-controller:local
      restartPolicy: Always
      serviceAccountName: env-injector-controller-sa
